# Generated by Django 5.2 on 2025-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfriendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_game_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
