# Generated by Django 5.2 on 2025-05-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='level',
            field=models.TextField(),
        ),
    ]
