# Generated by Django 5.2 on 2025-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_alter_diagnostic_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSection',
            fields=[
                ('id', models.IntegerField(help_text='Numeric ID that matches the section number in the learning path.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the learning section.', max_length=255)),
                ('description', models.TextField(help_text='The full description of the section. Supports long text, paragraphs, and special characters for formulas.')),
            ],
        ),
    ]
