# Generated by Django 5.2 on 2025-06-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_learningsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.IntegerField(help_text='ID numérico de la pregunta (ej: 1, 2, 3...)', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='El texto completo de la pregunta.')),
                ('section_block', models.CharField(help_text="El bloque de secciones que cubre esta pregunta (ej: '1-4').", max_length=10)),
            ],
            options={
                'verbose_name': 'Diagnostic Question',
                'verbose_name_plural': 'Diagnostic Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_identifier', models.CharField(help_text="El identificador de la opción (ej: 'a', 'b', 'c', 'd').", max_length=1)),
                ('text', models.TextField(help_text='El texto completo de la opción de respuesta.')),
                ('assigned_modules', models.JSONField(default=list, help_text='Una lista JSON de los IDs de los módulos a asignar si se elige esta respuesta.')),
                ('question', models.ForeignKey(help_text='La pregunta a la que pertenece esta respuesta.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.diagnosticquestion')),
            ],
            options={
                'ordering': ['question', 'option_identifier'],
                'unique_together': {('question', 'option_identifier')},
            },
        ),
    ]
