# Generated by Django 5.2 on 2025-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_diagnosticquestion_answeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsection',
            name='preference',
            field=models.CharField(blank=True, choices=[('loans', 'Loans'), ('investments', 'Investments')], help_text='The preference this section belongs to, either loans or investments.', max_length=11, null=True),
        ),
    ]
