# Generated by Django 5.2 on 2025-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_learningsection_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsection',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, help_text='An index for ordering the sections within the app.'),
        ),
    ]
