# Generated by Django 5.2 on 2025-06-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_learningsection_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningsection',
            old_name='index',
            new_name='learning_index',
        ),
    ]
