# Generated by Django 5.2 on 2025-06-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_rename_index_learningsection_learning_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticquestion',
            name='preference',
            field=models.CharField(blank=True, choices=[('loans', 'Loans'), ('investments', 'Investments')], help_text='The preference this section belongs to, either loans or investments.', max_length=11, null=True),
        ),
    ]
