# Generated by Django 5.2 on 2025-06-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_diagnosticquestion_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='modules',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='motivation',
            field=models.TextField(blank=True, help_text="Motivation for taking the diagnostic, e.g., 'I want to improve my financial literacy.'", null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='response_tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
