# Generated by Django 5.2 on 2025-06-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0009_diagnostic_modules_diagnostic_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
