# Generated by Django 5.2 on 2025-06-16 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('investment', 'Investment'), ('loan', 'Loan')], max_length=20)),
                ('first_user_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_user_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_second_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
