# Generated by Django 5.2 on 2025-05-31 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodules', '0001_initial'),
        ('learningpaths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=50)),
                ('order_index', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learningpaths.learningpath')),
            ],
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
