# Generated by Django 5.2 on 2025-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodules', '0002_learningmodule_delete_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
