# Generated by Django 5.2 on 2025-06-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodules', '0003_learningmodule_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodule',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
