# Generated by Django 5.2 on 2025-06-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningmodules', '0004_alter_learningmodule_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
