# Generated by Django 5.2 on 2025-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_pre_module',
            field=models.BooleanField(default=False),
        ),
    ]
